import type { FunctionConfigInput } from './types.js';

const parameter = (
  name: string,
  label: string,
  min: number,
  max: number,
  step: number,
  defaultValue: number,
) => ({ name, label, min, max, step, default: defaultValue });

export const defaultFunctions: FunctionConfigInput[] = [
  {
    name: 'Sine Function',
    slug: 'sine-function',
    category: 'Basic Functions',
    description: '观察振幅 A 与角频率 B 如何改变正弦波的高度和疏密。',
    expression: 'A * sin(B * x)',
    formula: 'f(x)=A\\sin(Bx)',
    parameters: [parameter('A', 'A', 0.1, 3, 0.1, 1), parameter('B', 'B', 0.1, 5, 0.1, 1)],
    xMin: -6.28,
    xMax: 6.28,
    yMin: -3.2,
    yMax: 3.2,
    sampleCount: 500,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Cosine Function',
    slug: 'cosine-function',
    category: 'Basic Functions',
    description: '余弦函数是从最高点开始的周期函数，可调节振幅与频率。',
    expression: 'A * cos(B * x)',
    formula: 'f(x)=A\\cos(Bx)',
    parameters: [parameter('A', 'A', 0.1, 3, 0.1, 1), parameter('B', 'B', 0.1, 5, 0.1, 1)],
    xMin: -6.28,
    xMax: 6.28,
    yMin: -3.2,
    yMax: 3.2,
    sampleCount: 500,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Tangent Function',
    slug: 'tangent-function',
    category: 'Basic Functions',
    description: '观察正切函数的周期以及渐近线附近的快速变化。',
    expression: 'tan(B * x)',
    formula: 'f(x)=\\tan(Bx)',
    parameters: [parameter('B', 'B', 0.25, 2, 0.05, 1)],
    xMin: -3.14,
    xMax: 3.14,
    yMin: -8,
    yMax: 8,
    sampleCount: 600,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Exponential Function',
    slug: 'exponential-function',
    category: 'Basic Functions',
    description: '改变增长率 k，观察指数增长与指数衰减。',
    expression: 'exp(k * x)',
    formula: 'f(x)=e^{kx}',
    parameters: [parameter('k', 'k', -2, 2, 0.1, 1)],
    xMin: -4,
    xMax: 4,
    yMin: 0,
    yMax: 12,
    sampleCount: 400,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Logarithmic Function',
    slug: 'logarithmic-function',
    category: 'Basic Functions',
    description: '对数函数只在 x > 0 时有实数值，参数 b 控制纵向缩放。',
    expression: 'b * log(x)',
    formula: 'f(x)=b\\ln(x)',
    parameters: [parameter('b', 'b', 0.2, 3, 0.1, 1)],
    xMin: 0.05,
    xMax: 10,
    yMin: -4,
    yMax: 7,
    sampleCount: 400,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Square Root Function',
    slug: 'square-root-function',
    category: 'Basic Functions',
    description: '平方根函数从原点出发，并随着 x 增大逐渐变平缓。',
    expression: 'a * sqrt(x)',
    formula: 'f(x)=a\\sqrt{x}',
    parameters: [parameter('a', 'a', 0.2, 3, 0.1, 1)],
    xMin: 0,
    xMax: 16,
    yMin: 0,
    yMax: 12,
    sampleCount: 350,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Gamma Function',
    slug: 'gamma-function',
    category: 'Special Functions',
    description: 'Gamma 函数把阶乘推广到实数与复数；这里可调节横向偏移 α。',
    expression: 'gamma(x + alpha)',
    formula: 'f(x)=\\Gamma(x+\\alpha)',
    parameters: [parameter('alpha', 'α', 0, 4, 0.1, 1)],
    xMin: 0.05,
    xMax: 5,
    yMin: 0,
    yMax: 25,
    sampleCount: 450,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Beta Function',
    slug: 'beta-function',
    category: 'Special Functions',
    description: '固定横轴为 x，改变参数 y，观察贝塔函数 B(x,y) 的形状。',
    expression: 'beta(x, y)',
    formula: 'f(x)=B(x,y)',
    parameters: [parameter('y', 'y', 0.2, 8, 0.1, 2)],
    xMin: 0.1,
    xMax: 8,
    yMin: 0,
    yMax: 5,
    sampleCount: 450,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Error Function',
    slug: 'error-function',
    category: 'Special Functions',
    description: '误差函数常用于高斯积分、概率论与扩散方程。',
    expression: 'erf(scale * x)',
    formula: 'f(x)=\\operatorname{erf}(sx)',
    parameters: [parameter('scale', 's', 0.2, 3, 0.1, 1)],
    xMin: -3,
    xMax: 3,
    yMin: -1.1,
    yMax: 1.1,
    sampleCount: 450,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Hyperbolic Sine',
    slug: 'hyperbolic-sine',
    category: 'Hyperbolic Functions',
    description: '双曲正弦由指数函数组合而成，关于原点中心对称。',
    expression: 'a * sinh(x)',
    formula: 'f(x)=a\\sinh(x)',
    parameters: [parameter('a', 'a', 0.2, 2, 0.1, 1)],
    xMin: -3,
    xMax: 3,
    yMin: -10,
    yMax: 10,
    sampleCount: 400,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Hyperbolic Cosine',
    slug: 'hyperbolic-cosine',
    category: 'Hyperbolic Functions',
    description: '双曲余弦是偶函数，图像类似悬链线。',
    expression: 'a * cosh(x)',
    formula: 'f(x)=a\\cosh(x)',
    parameters: [parameter('a', 'a', 0.2, 2, 0.1, 1)],
    xMin: -3,
    xMax: 3,
    yMin: 0,
    yMax: 12,
    sampleCount: 400,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Hyperbolic Tangent',
    slug: 'hyperbolic-tangent',
    category: 'Hyperbolic Functions',
    description: '双曲正切将任意实数压缩到 -1 与 1 之间。',
    expression: 'tanh(k * x)',
    formula: 'f(x)=\\tanh(kx)',
    parameters: [parameter('k', 'k', 0.2, 5, 0.1, 1)],
    xMin: -5,
    xMax: 5,
    yMin: -1.1,
    yMax: 1.1,
    sampleCount: 450,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Normal Distribution',
    slug: 'normal-distribution',
    category: 'Probability Distributions',
    description: '拖动均值 μ 移动钟形曲线，调整标准差 σ 改变曲线的宽窄。',
    expression: 'normalPdf(x, mu, sigma)',
    formula: 'f(x)=\\frac{1}{\\sigma\\sqrt{2\\pi}}e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}',
    parameters: [parameter('mu', 'μ', -3, 3, 0.1, 0), parameter('sigma', 'σ', 0.2, 3, 0.1, 1)],
    xMin: -8,
    xMax: 8,
    yMin: 0,
    yMax: 1,
    sampleCount: 550,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Beta Distribution',
    slug: 'beta-distribution',
    category: 'Probability Distributions',
    description: '用 α 与 β 探索定义在 0 到 1 之间的多种概率密度形状。',
    expression: 'betaPdf(x, alpha, betaValue)',
    formula: 'f(x)=\\frac{x^{\\alpha-1}(1-x)^{\\beta-1}}{B(\\alpha,\\beta)}',
    parameters: [parameter('alpha', 'α', 0.2, 8, 0.1, 2), parameter('betaValue', 'β', 0.2, 8, 0.1, 5)],
    xMin: 0.001,
    xMax: 0.999,
    yMin: 0,
    yMax: 5,
    sampleCount: 500,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Gamma Distribution',
    slug: 'gamma-distribution',
    category: 'Probability Distributions',
    description: '形状参数 k 与尺度参数 θ 共同决定 Gamma 分布的偏斜和扩散程度。',
    expression: 'gammaPdf(x, k, theta)',
    formula: 'f(x)=\\frac{x^{k-1}e^{-x/\\theta}}{\\Gamma(k)\\theta^k}',
    parameters: [parameter('k', 'k', 0.5, 10, 0.1, 2), parameter('theta', 'θ', 0.2, 4, 0.1, 2)],
    xMin: 0.001,
    xMax: 20,
    yMin: 0,
    yMax: 1,
    sampleCount: 550,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'Poisson Distribution',
    slug: 'poisson-distribution',
    category: 'Probability Distributions',
    description: '调整平均发生次数 λ，观察离散事件数量的概率质量如何移动。',
    expression: 'poissonPmf(x, lambda)',
    formula: 'P(X=x)=\\frac{\\lambda^x e^{-\\lambda}}{x!}',
    parameters: [parameter('lambda', 'λ', 0.5, 15, 0.5, 4)],
    xMin: 0,
    xMax: 25,
    yMin: 0,
    yMax: 0.5,
    sampleCount: 26,
    chartType: 'bar',
    isBuiltin: true,
  },
  {
    name: 'Binomial Distribution',
    slug: 'binomial-distribution',
    category: 'Probability Distributions',
    description: '调整试验次数 n 与成功概率 p，观察成功次数的离散分布。',
    expression: 'binomialPmf(x, n, p)',
    formula: 'P(X=x)={n\\choose x}p^x(1-p)^{n-x}',
    parameters: [parameter('n', 'n', 1, 30, 1, 12), parameter('p', 'p', 0.05, 0.95, 0.05, 0.5)],
    xMin: 0,
    xMax: 30,
    yMin: 0,
    yMax: 0.5,
    sampleCount: 31,
    chartType: 'bar',
    isBuiltin: true,
  },
  {
    name: 'Sigmoid',
    slug: 'sigmoid',
    category: 'Neural Functions',
    description: '神经网络常用激活函数，把实数输入压缩到 0 与 1 之间。',
    expression: '1 / (1 + exp(-k * x))',
    formula: 'f(x)=\\frac{1}{1+e^{-kx}}',
    parameters: [parameter('k', 'k', 0.2, 5, 0.1, 1)],
    xMin: -8,
    xMax: 8,
    yMin: -0.05,
    yMax: 1.05,
    sampleCount: 450,
    chartType: 'line',
    isBuiltin: true,
  },
  {
    name: 'ReLU',
    slug: 'relu',
    category: 'Neural Functions',
    description: 'ReLU 保留正数并把负数变为 0，是最常见的神经网络激活函数之一。',
    expression: 'a * max(0, x)',
    formula: 'f(x)=a\\max(0,x)',
    parameters: [parameter('a', 'a', 0.2, 3, 0.1, 1)],
    xMin: -6,
    xMax: 6,
    yMin: -0.5,
    yMax: 10,
    sampleCount: 400,
    chartType: 'line',
    isBuiltin: true,
  },
];
